modLoader="javafml"
loaderVersion="[40,41)"

issueTrackerURL="https://github.com/CC-Next/CC-Next/issues"
logoFile="pack.png"

license="ComputerCraft Public License (https://raw.githubusercontent.com/dan200/ComputerCraft/master/LICENSE)"

[[mods]]
modId="computercraft"
version="${file.jarVersion}"
displayName="CC: Next"
displayURL="https://github.com/CC-Next/CC-Next"

credits="Created by Daniel Ratcliffe (@DanTwoHundred)"
authors="Daniel Ratcliffe, Aaron Mills, SquidDev"
description='''
Bleeding edge CC:T builds. Expect bugs.
'''

[[dependencies.computercraft]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.2,41)"
    ordering="NONE"
    side="BOTH"
