modLoader="javafml"
loaderVersion="[37,38)"

issueTrackerURL="https://github.com/CC-Next/CC-Next/issues"
logoFile="pack.png"

license="ComputerCraft Public License (https://raw.githubusercontent.com/dan200/ComputerCraft/master/LICENSE)"

[[mods]]
modId="computercraft"
version="${file.jarVersion}"
displayURL="https://github.com/CC-Next/CC-Next"

credits="Created by Daniel Ratcliffe (@DanTwoHundred)"
authors="Daniel Ratcliffe, Aaron Mills, SquidDev"
displayName="CC: Next"
description='''
Bleeding edge CC:T builds. Expect bugs.
'''

[[dependencies.computercraft]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.85,38)"
    ordering="NONE"
    side="BOTH"
