modLoader="javafml"
loaderVersion="[36,37)"

issueTrackerURL="https://github.com/CC-Next/CC-Next/issues"
displayURL="https://github.com/CC-Next/CC-Next"
logoFile="pack.png"

credits="Created by Daniel Ratcliffe (@DanTwoHundred)"
authors="Daniel Ratcliffe, Aaron Mills, SquidDev"
license="ComputerCraft Public License (https://raw.githubusercontent.com/dan200/ComputerCraft/master/LICENSE)"

[[mods]]
modId="computercraft"
version="${version}"
displayName="CC: Next"
description='''
Bleeding edge CC:T builds. Expect bugs.
'''

[[dependencies.computercraft]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.20,37)"
    ordering="NONE"
    side="BOTH"
