name: All

on:
  workflow_dispatch:
  push:
    branches:
    - 'CCN/*'
    - '!CNN/main' # not the orphan branch
    - 'MC-*'
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: update mc-1.17.x
      uses: ./.github/actions/tracking
      with:
        branch: mc-1.17.x
        github-token: ${{ inputs.GITHUB_TOKEN }}


