name: All

on:
  workflow_dispatch:
  push:
    branches:
    - 'CCN/*'
    - '!CNN/main' # not the orphan branch
    - 'MC-*'
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
    - run: pwd


