name: generic-updater

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      upstream-repo:
        required: false
        type: string
        default: https://github.com/cc-tweaked/CC-Tweaked.git
      upstream-branch:
        required: false
        type: string
        default: ""
    outputs:
      upstreamCommit:
        description: "The commit ID that upstream is at."
        value: ${{ jobs.update-branch.outputs.upstreamCommit }}

jobs:
  update-branch:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: add upstream
      if: ${{ !env.ACT }}
      run: git remote add upstream ${{ inputs.upstream-repo }}

    - name: default upstream-branch # because setting the defualt to a var didn't work
      run: |
        if "${{ inputs.upstream-branch }}" == ""; then
          echo "upstream-branch=${{ inputs.branch }}" >> $GITHUB_ENV;
        else
          echo "upstream-branch=${{ inputs.upstream-branch }}" >> $GITHUB_ENV;
        done
        return 0

    - name: pull upstream
      run: |
        git checkout ${{ inputs.branch }}
        git pull upstream ${{ inputs.upstream-branch }}

    # TODO: get the commit id from upstream and output it

    - name: push changes
      uses: dciborow/commit@0.0.1
      if: ${{ env.ACT || success() }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: '${{ inputs.branch }}'
