name: generic-tracking-merger

on:
  workflow_call:
    inputs:
      to-branch:
        required: true
        type: string
      from-branch:
        required: true
        type: string

jobs:
  update-branch:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token TODO: does this need to be false?
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: merge
      uses: bambamboole/gha-upmerge@v1.0.1
      with:
        from_branch: ${{ inputs.from-branch }}
        to_branch: ${{ inputs.to-branch }}
        push_token: ${{ secrets.GITHUB_TOKEN }}

    - name: push changes
      uses: dciborow/commit@0.0.1
      if: ${{ env.ACT || success() }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: '${{ inputs.branch }}'


