name: generic-tracking-updater

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
# TODO: commit and then build so that we have a commit id to put in the release version number
jobs:
  update-branch:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: add upstream
      if: ${{ !env.ACT }}
      run: git remote add upstream https://github.com/cc-tweaked/CC-Tweaked.git

    - name: pull upstream
      run: |
        git checkout ${{ inputs.branch }}
        git pull upstream ${{ inputs.branch }}

    - name: push changes
      uses: dciborow/commit@0.0.1
      if: ${{ env.ACT || success() }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: '${{ inputs.branch }}'
