name: generic-merger

on:
  workflow_call:
    inputs:
      to-branch:
        required: true
        type: string
      from-branch:
        required: true
        type: string

jobs:
  update-branch:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token TODO: does this need to be false?
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: put gh token into env
      run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV


#    - name: merge and force push
#      uses: bambamboole/gha-upmerge@v1.0.1
#      with:
#        from_branch: ${{ inputs.from-branch }}
#        to_branch: ${{ inputs.to-branch }}

    - name: remove gh token from env
      run: echo "GITHUB_TOKEN=purged" >> $GITHUB_ENV



