name: MC-1_16_x

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
    - 'CCN/*'
    - '!CNN/main' # not the orphan branch
    - 'MC-*'
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build-mc-1_16_x:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: add upstream
      if: ${{ !env.ACT }}
      run: git remote add upstream https://github.com/cc-tweaked/CC-Tweaked.git

    - name: pull upstream
      run: |
        git checkout mc-1.16.x
        git pull upstream mc-1.16.x

    - name: install xvfb
      if: ${{ env.ACT }} # https://github.com/nektos/act#skipping-steps
      run: apt-get update && apt-get install -y xvfb #firefox

    - name: Set up Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Cache gradle dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('gradle.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Disable Gradle daemon
      run: |
        mkdir -p ~/.gradle
        echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties

    - name: Build with Gradle
      run: |
        ./gradlew assemble || ./gradlew assemble
        ./gradlew downloadAssets || ./gradlew downloadAssets
        xvfb-run ./gradlew build

    - name: Upload Jar
      uses: actions/upload-artifact@v2
      if: ${{ env.ACT || success() }} # gradle test seems to sometimes time out or something, checking if we are acting allows us to pretend that all the tests passed
      with:
        name: CC-Next
        path: build/libs

    - name: push changes # I need the commit id in the version number, which means that I'm going to want to have the push changes before I build
                         # two jobs? one to merge and the other to build?
      uses: dciborow/commit@0.0.1
      if: ${{ env.ACT || success() }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'mc-1.16.x'
