name: tracking-update-and-build

on:
  workflow_dispatch:
  push:
    # branches:
    # - 'MC-'
  # schedule:
  #   - cron:  '0 0 * * *'

jobs:
  update-mc-1_16_x:
    uses: CC-Next/CC-Next/.github/workflows/generic-tracking-updater.yml@CCN/main
    with:
      branch: mc-1.16.x
  build-mc-1_16_x:
    uses: CC-Next/CC-Next/.github/workflows/generic-tracking-builder.yml@CCN/main
    needs: update-mc-1_16_x
    with:
      branch: mc-1.16.x

  update-mc-1_17_x:
    uses: CC-Next/CC-Next/.github/workflows/generic-tracking-updater.yml@CCN/main
    with:
      branch: mc-1.17.x
  merge-mc-1_17_x-with-mc-1_16_x:
    uses: CC-Next/CC-Next/.github/workflows/generic-tracking-merger.yml@CCN/main
    needs: [update-mc-1_16_x, update-mc-1_17_x]
    with:
      to-branch: mc-1.17.x
      from-branch: origin/mc-1.16.x
  build-mc-1_17_x:
    uses: CC-Next/CC-Next/.github/workflows/generic-tracking-builder.yml@CCN/main
    needs: merge-mc-1_17_x-with-mc-1_16_x
    with:
      branch: mc-1.17.x

  update-mc-1_18_x:
    uses: CC-Next/CC-Next/.github/workflows/generic-tracking-updater.yml@CCN/main
    with:
      branch: mc-1.18.x
  merge-mc-1_18_x-with-mc-1_17_x:
    uses: CC-Next/CC-Next/.github/workflows/generic-tracking-merger.yml@CCN/main
    needs: [update-mc-1_18_x, merge-mc-1_17_x-with-mc-1_16_x]
    with:
      to-branch: mc-1.18.x
      from-branch: origin/mc-1.17.x
  build-mc-1_18_x:
    uses: CC-Next/CC-Next/.github/workflows/generic-tracking-builder.yml@CCN/main
    needs: merge-mc-1_18_x-with-mc-1_17_x
    with:
      branch: mc-1.18.x

