name: update-and-build

on:
  workflow_dispatch:
  push:
     # branches:
     # - 'MC-*'
  schedule:
    - cron:  '0 0 * * *'

jobs:

  update-mc-1_16_x:
    uses: CC-Next/CC-Next/.github/workflows/generic-updater.yml@CCN/main
    with:
      branch: mc-1.16.x

  build-mc-1_16_x:
    uses: CC-Next/CC-Next/.github/workflows/generic-builder.yml@CCN/main
    needs: update-mc-1_16_x
    with:
      branch: mc-1.16.x
      mcVersion: mc-1.16.x
      upstreamCommit:  ${{ needs.update-mc-1_16_x.outputs.upstreamCommit }}

#####

  update-mc-1_17_x:
    uses: CC-Next/CC-Next/.github/workflows/generic-updater.yml@CCN/main
    with:
      branch: mc-1.17.x

  merge-mc-1_16_x-into-mc-1_17_x:
    uses: CC-Next/CC-Next/.github/workflows/generic-merger.yml@CCN/main
    needs: [update-mc-1_16_x, update-mc-1_17_x]
    with:
      to-branch: mc-1.17.x
      from-branch: mc-1.16.x

  build-mc-1_17_x:
    uses: CC-Next/CC-Next/.github/workflows/generic-builder.yml@CCN/main
    needs: [update-mc-1_17_x, merge-mc-1_16_x-into-mc-1_17_x]
    with:
      branch: mc-1.17.x
      mcVersion: mc-1.17.x
      upstreamCommit:  ${{ needs.update-mc-1_17_x.outputs.upstreamCommit }}

#####

  update-mc-1_18_x:
    uses: CC-Next/CC-Next/.github/workflows/generic-updater.yml@CCN/main
    with:
      branch: mc-1.18.x

  merge-mc-1_17_x-into-mc-1_18_x:
    uses: CC-Next/CC-Next/.github/workflows/generic-merger.yml@CCN/main
    needs: [update-mc-1_18_x, merge-mc-1_16_x-into-mc-1_17_x]
    with:
      to-branch: mc-1.18.x
      from-branch: mc-1.17.x

  build-mc-1_18_x:
    uses: CC-Next/CC-Next/.github/workflows/generic-builder.yml@CCN/main
    needs: [update-mc-1_18_x, merge-mc-1_17_x-into-mc-1_18_x]
    with:
      branch: mc-1.18.x
      mcVersion: mc-1.18.x
      upstreamCommit:  ${{ needs.update-mc-1_18_x.outputs.upstreamCommit }}

 ###############
 ###  ###
 # #  # #    ###
 ###  ###    ##
 #    #  #    ##
 #    #   #  ###
 ###############

 ###########
 #990 Lua5.2
 ###########

 ## I feel like what I should be doing is pulling from CC:T and then merging in the PR

  update-mc-1_16_x_PR990:
    uses: CC-Next/CC-Next/.github/workflows/generic-updater.yml@CCN/main
    with:
      branch: CCN/mc-1.16.x+PR990
      upstream-repo: https://github.com/MCJack123/CC-Tweaked.git
      upstream-branch: feature/lua-5.2

  merge-mc-1_16_x-into-mc-1_16_x_PR990:
    uses: CC-Next/CC-Next/.github/workflows/generic-merger.yml@CCN/main
    needs: [update-mc-1_16_x, update-mc-1_16_x_PR990]
    with:
      to-branch: CCN/mc-1.16.x+PR990
      from-branch: mc-1.16.x

  build-mc-1_16_x_PR990:
    uses: CC-Next/CC-Next/.github/workflows/generic-builder.yml@CCN/main
    needs: [update-mc-1_16_x, merge-mc-1_16_x-into-mc-1_16_x_PR990]
    with:
      branch: mc-1.16.x
      upstreamCommit:  ${{ needs.update-mc-1_16_x.outputs.upstreamCommit }}
      extraVersionInfo: PR990
      mcVersion: mc-1.16.x
      preBuildAction: |
        wget 'https://github.com/CC-Next/Cobalt/releases/download/0.5.4%2B859205c%2B484ae62%2B(PR50)/Cobalt-0.5.4+859205c+484ae62+.PR50.jar'


#####

  merge-mc-1_17_x-into-mc-1_17_x_PR990:
    uses: CC-Next/CC-Next/.github/workflows/generic-merger.yml@CCN/main
    needs: [update-mc-1_17_x]
    with:
      to-branch: CCN/mc-1.17.x+PR990
      from-branch: mc-1.17.x

  merge-mc-1_16_x_PR990-into-mc-1_17_x_PR990:
    uses: CC-Next/CC-Next/.github/workflows/generic-merger.yml@CCN/main
    needs: [merge-mc-1_17_x-into-mc-1_17_x_PR990, merge-mc-1_16_x-into-mc-1_16_x_PR990]
    with:
      to-branch: CCN/mc-1.17.x+PR990
      from-branch: CCN/mc-1.16.x+PR990

  build-mc-1_17_x_PR990:
    uses: CC-Next/CC-Next/.github/workflows/generic-builder.yml@CCN/main
    needs: [update-mc-1_17_x, merge-mc-1_16_x_PR990-into-mc-1_17_x_PR990]
    with:
      branch: CCN/mc-1.17.x+PR990
      upstreamCommit:  ${{ needs.update-mc-1_17_x.outputs.upstreamCommit }}
      extraVersionInfo: PR990
      mcVersion: mc-1.17.x
      preBuildAction: |
        wget 'https://github.com/CC-Next/Cobalt/releases/download/0.5.4%2B859205c%2B484ae62%2B(PR50)/Cobalt-0.5.4+859205c+484ae62+.PR50.jar'

#####

  merge-mc-1_18_x-into-mc-1_18_x_PR990:
    uses: CC-Next/CC-Next/.github/workflows/generic-merger.yml@CCN/main
    needs: [update-mc-1_18_x]
    with:
      to-branch: CCN/mc-1.18.x+PR990
      from-branch: mc-1.18.x

  merge-mc-1_17_x_PR990-into-mc-1_18_x_PR990:
    uses: CC-Next/CC-Next/.github/workflows/generic-merger.yml@CCN/main
    needs: [merge-mc-1_18_x-into-mc-1_18_x_PR990, merge-mc-1_17_x-into-mc-1_17_x_PR990]
    with:
      to-branch: CCN/mc-1.18.x+PR990
      from-branch: CCN/mc-1.17.x+PR990

  build-mc-1_18_x_PR990:
    uses: CC-Next/CC-Next/.github/workflows/generic-builder.yml@CCN/main
    needs: [update-mc-1_18_x, merge-mc-1_17_x_PR990-into-mc-1_18_x_PR990]
    with:
      branch: CCN/mc-1.18.x+PR990
      upstreamCommit:  ${{ needs.update-mc-1_18_x.outputs.upstreamCommit }}
      extraVersionInfo: PR990
      mcVersion: mc-1.18.x
      preBuildAction: |
        wget 'https://github.com/CC-Next/Cobalt/releases/download/0.5.4%2B859205c%2B484ae62%2B(PR50)/Cobalt-0.5.4+859205c+484ae62+.PR50.jar'

